name: couldai_user_app
description: "Application d'Analyse Strat√©gique 5G Tunisie"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # Navigation
  go_router: ^14.0.0
  # UI & Design
  google_fonts: ^6.1.0
  fl_chart: ^0.66.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  # State Management & Utilities
  provider: ^6.1.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
